name: VORTICE OCI Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Show submodule status (diagnostic)
        run: |
          git submodule status || true
          echo "Submodule directories:"
          awk '/path = / {print $3}' .gitmodules 2>/dev/null | while read d; do
            echo "== $d =="
            ls -la "$d" || true
          done

      - name: Build the Docker image
        run: |
          docker build . \
            --file Containerfile \
            --tag vortice:$(date +%s)

